#cloud-config

write_files:
  - path: "/etc/systemd/system/kubelet.service.d/0-containerd.conf"
    permissions: "0755"
    content: |
      [Service]
      Environment="KUBELET_EXTRA_ARGS=--container-runtime=remote --runtime-request-timeout=15m --container-runtime-endpoint=unix:///run/containerd/containerd.sock"
  - path: "/etc/systemd/system/kubelet.service"
    permissions: "0755"
    content: |
      [Unit]
      Description=Kubernetes Kubelet
      Documentation=https://github.com/kubernetes/kubernetes
      After=containerd.service
      Requires=containerd.service

      [Service]
      ExecStart=/usr/local/bin/kubelet \
        --allow-privileged=true \
        --anonymous-auth=false \
        --authorization-mode=Webhook \
        --client-ca-file=/etc/kubernetes/ssl/ca.pem \
        --cluster-dns=${DNS_SERVICE_IP} \
        --cluster-domain=cluster.local \
        --container-runtime=remote \
        --container-runtime-endpoint=unix:///run/containerd/containerd.sock \
        --image-pull-progress-deadline=2m \
        --kubeconfig=/etc/kubernetes/kubelet.kubeconfig \
        --hostname-override=${HOSTNAME}  \
        --network-plugin=cni \
        --pod-cidr=${POD_CIDR} \
        --register-node=true \
        --rotate-certificates=true \
        --runtime-request-timeout=15m \
        --tls-cert-file=/var/lib/kubelet/pki/kubelet.crt \
        --tls-private-key-file=/var/lib/kubelet/pki/kubelet.key \
        --v=2
      Restart=on-failure
      RestartSec=5

      [Install]
      WantedBy=multi-user.target
  - path: "/etc/systemd/system/kube-proxy.service"
    permissions: "0755"
    content: |
      [Unit]
      Description=Kubernetes Kube Proxy
      Documentation=https://github.com/kubernetes/kubernetes

      [Service]
      ExecStart=/usr/local/bin/kube-proxy \
        --cluster-cidr=${POD_CIDR} \
        --kubeconfig=/var/lib/kube-proxy/kube-proxy.kubeconfig \
        --proxy-mode=iptables \
        --v=2
      Restart=on-failure
      RestartSec=5

      [Install]
      WantedBy=multi-user.target

